version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8089:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: matricula
    depends_on:
      - db
